import matplotlib.pyplot as plt
from data_analysis import df  
plt.figure(figsize=(10,6))
plt.plot(df['Year'], df['Price_per_Barrel'], marker='o', linestyle='-', label='Actual Price')
plt.plot(df['Year'], df['Predicted_Price'], marker='x', linestyle='--', label='Predicted Price')
plt.xlabel('Year')
plt.ylabel('Price per Barrel')
plt.title('Texas Oil Price: Actual vs Predicted')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

plt.plot(df['Year'], df['Price_per_Barrel'], marker='o', label='Actual', color='blue')
plt.plot(df['Year'], df['Predicted_Price'], marker='x', label='Predicted', color='red')
plt.xlabel('Year')
plt.ylabel('Price per Barrel ($)')
plt.title('Time Series: Actual vs Predicted Price per Barrel')
plt.legend()
plt.show()
